version: '3'

services:
  wechat2tg:
    image: ghcr.io/cuijizhu/wechat2tg/wechat2tg:latest
    container_name: wx2tg
    volumes:
      - ./config:/app/config
    environment:
      - BOT_TOKEN=
      # - HOST=
      # - PORT=
      # 代理种类
      - PROTOCOL=socks5
      # 用户名密码可选
      # - USERNAME=
      # - PASSWORD=
    restart: unless-stopped
