version: '3'

services:
  wechat2tg:
    image: finalpi/wechat2tg:latest
    container_name: wx2tg
    environment:
      - BOT_TOKEN=''
      - HOST=''
      - PORT=''
      # 代理种类
      - PROTOCOL='socks5'
      # 用户名密码可选
      # - USERNAME=
      # - PASSWORD=
    restart: unless-stopped
